spring:
  application:
    name: harbour
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/harbour}
    username: ${DB_USERNAME:harbour}
    password: ${DB_PASSWORD:harbour}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug

harbour:
  open-meteo:
    weather-url: https://api.open-meteo.com
